# Generated by Django 4.2.3 on 2023-07-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresas",
            fields=[
                ("nombre_empresa", models.CharField(max_length=150)),
                ("direccion_empresa", models.CharField(max_length=200)),
                (
                    "rut_empresa",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("telefono", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Empleados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empleado", models.CharField(max_length=150)),
                ("rut_empleado", models.CharField(max_length=12)),
                ("email", models.CharField(max_length=50)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.empresas"
                    ),
                ),
            ],
        ),
    ]
